### ISSUE TITLE
RESPONSE_TIMEOUT = 1.2

### ISSUE THREAD

**Issue by Goodsmileduck** [surik00/aioalice#5]
Теперь таймаут можно увеличить =)

**Comment by surik00** [comment]
Выставлю 2.7, так как таймаут увеличили до 3 секунд, включая сетевое время

**Comment by Goodsmileduck** [comment]
+1

**Comment by surik00** [comment]
Fixed in release 1.2.4:
https://github.com/surik00/aioalice/releases/tag/1.2.4
